input_number:
  forno_durata_minuti:
    name: Durata Forno (min)
    min: 1
    max: 120
    step: 1
    unit_of_measurement: min

script:
  forno_imposta_durata:
    alias: Forno - Imposta durata corretta
    mode: single
    sequence:
      - variables:
          minuti: "{{ states('input_number.forno_durata_minuti') | int }}"
          secondi: "{{ minuti * 60 }}"
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_bsh_common_option_duration
        data:
          value: "{{ secondi }}"

# Applica automaticamente la temperatura quando lo slider cambia
automation:
  - alias: Forno - Applica temperatura da slider
    mode: restart
    trigger:
      - platform: state
        entity_id: number.bosch_383120532719000097_001_cooking_oven_option_setpointtemperature
    action:
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_cooking_oven_option_setpointtemperature
        data:
          value: "{{ trigger.to_state.state }}"
