input_number:
  forno_durata_minuti:
    name: Durata Forno (min)
    min: 1
    max: 120
    step: 1
    unit_of_measurement: min

script:
  forno_imposta_durata:
    alias: Forno - Imposta durata corretta
    mode: single
    sequence:
      - variables:
          minuti: "{{ states('input_number.forno_durata_minuti') | int }}"
          secondi: "{{ minuti * 60 }}"
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_bsh_common_option_duration
        data:
          value: "{{ secondi }}"

  forno_tosta:
    alias: Forno - Tosta pane
    mode: single
    sequence:
      - service: select.select_option
        data:
          entity_id: select.bosch_383120532719000097_001_bsh_common_setting_powerstate
          option: BSH.Common.EnumType.PowerState.On
      - service: select.select_option
        data:
          entity_id: select.bosch_383120532719000097_001_programs
          option: Cooking.Oven.Program.HeatingMode.HotAirGrilling
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_bsh_common_option_duration
        data:
          value: 420
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_cooking_oven_option_setpointtemperature
        data:
          value: 120

  forno_scalda:
    alias: Forno - Scalda cibo
    mode: single
    sequence:
      - service: select.select_option
        data:
          entity_id: select.bosch_383120532719000097_001_bsh_common_setting_powerstate
          option: BSH.Common.EnumType.PowerState.On
      - service: select.select_option
        data:
          entity_id: select.bosch_383120532719000097_001_programs
          option: Cooking.Oven.Program.HeatingMode.KeepWarm
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_bsh_common_option_duration
        data:
          value: 600
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_cooking_oven_option_setpointtemperature
        data:
          value: 90

# Applica automaticamente la temperatura quando lo slider cambia
automation:
  - alias: Forno - Applica temperatura da slider
    mode: restart
    trigger:
      - platform: state
        entity_id: number.bosch_383120532719000097_001_cooking_oven_option_setpointtemperature
    action:
      - service: number.set_value
        target:
          entity_id: number.bosch_383120532719000097_001_cooking_oven_option_setpointtemperature
        data:
          value: "{{ trigger.to_state.state }}"
