# ============================================================
# PRESENCE - AUTOMAZIONI BASATE SULLA PRESENZA
# ============================================================
# Gestisce tutte le automazioni legate alla presenza/posizione:
# - Ritorno a casa
# - Accensione automatica luci basata sulla posizione
# ============================================================

# ============================================================
# INPUT SELECT - Stanza attuale
# ============================================================
input_select:
  stanza_attuale:
    name: Stanza Attuale
    options:
      - Indeterminato
      - Soggiorno
      - Camera
      - Camera da Letto
      - Cucina
    initial: Indeterminato
    icon: mdi:home-search

# ============================================================
# INPUT BOOLEAN - Toggle Automazioni
# ============================================================
input_boolean:
  automazioni_luci:
    name: Automazioni Luci BLE
    icon: mdi:lightbulb-auto
    initial: "on"

# ============================================================
# TEMPLATE SENSORS - Rilevamento BLE
# ============================================================
template:
  - sensor:
      # Sensore RSSI (potenza segnale) - sostituisci con il tuo MAC device
      - name: "Moto G42 RSSI"
        unique_id: moto_g42_rssi
        unit_of_measurement: "dBm"
        state: >
          {% set rssi = state_attr('device_tracker.moto_g42', 'ble_rssi') %}
          {{ rssi if rssi is not none else none }}

      # Sensore distanza calcolata dal RSSI
      - name: "Moto G42 Distanza"
        unique_id: moto_g42_distanza
        unit_of_measurement: "m"
        state: >
          {% set rssi = state_attr('device_tracker.moto_g42', 'ble_rssi') | int(-999) %}
          {% if rssi > -999 %}
            {% set tx_power = -59 %}
            {% set distance = 10 ** ((tx_power - rssi) / (10 * 2)) %}
            {{ "%.1f" | format(distance) }}
          {% else %}
            {{ none }}
          {% endif %}

      # Sensore RSSI Pixel 9a
      - name: "Pixel 9a RSSI"
        unique_id: pixel_9a_rssi
        unit_of_measurement: "dBm"
        state: >
          {% set rssi = state_attr('device_tracker.pixel_9a', 'ble_rssi') %}
          {{ rssi if rssi is not none else none }}

      # Sensore distanza Pixel 9a
      - name: "Pixel 9a Distanza"
        unique_id: pixel_9a_distanza
        unit_of_measurement: "m"
        state: >
          {% set rssi = state_attr('device_tracker.pixel_9a', 'ble_rssi') | int(-999) %}
          {% if rssi > -999 %}
            {% set tx_power = -59 %}
            {% set distance = 10 ** ((tx_power - rssi) / (10 * 2)) %}
            {{ "%.1f" | format(distance) }}
          {% else %}
            {{ none }}
          {% endif %}

# ============================================================
# AUTOMAZIONI
# ============================================================
automation:
  # ========================================
  # RITORNO A CASA
  # ========================================
  - alias: Ritorno a Casa - Benvenuto
    mode: single
    description: "Accoglienza graduale luci quando rientri e la casa è spenta"
    trigger:
      - platform: state
        entity_id: device_tracker.moto_g42
        from: "not_home"
        to: "home"
      - platform: state
        entity_id: device_tracker.pixel_9a
        from: "not_home"
        to: "home"
    condition:
      # Verifica che NESSUNO fosse in casa prima (entrambi not_home)
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: "0" # moto_g42 trigger
              - condition: state
                entity_id: device_tracker.pixel_9a
                state: "not_home"
          - condition: and
            conditions:
              - condition: trigger
                id: "1" # pixel_9a trigger
              - condition: state
                entity_id: device_tracker.moto_g42
                state: "not_home"
    action:
      # Calcola intensità in base al momento della giornata
      - variables:
          is_below_horizon: "{{ is_state('sun.sun', 'below_horizon') }}"
          hour_now: "{{ now().hour }}"
          brightness_soggiorno: >
            {% if is_below_horizon %}40
            {% elif hour_now < 12 %}80
            {% else %}60
            {% endif %}
          brightness_camera: >
            {% if is_below_horizon %}60
            {% elif hour_now < 12 %}90
            {% else %}75
            {% endif %}

      # Accendi Gregg Soggiorno
      - service: script.set_zone_brightness
        data:
          zone_key: "gregg_soggiorno"
          brightness: "{{ brightness_soggiorno }}"

      # Accendi Gregg Cucina (stessa intensità del Soggiorno)
      - service: script.set_zone_brightness
        data:
          zone_key: "gregg_cucina"
          brightness: "{{ brightness_soggiorno }}"

      # Accendi Camera
      - service: script.set_zone_brightness
        data:
          zone_key: "led_camera"
          brightness: "{{ brightness_camera }}"
      # Notifica
      - service: !secret notify_service
        data:
          title: "🏠 Rientro a casa"
          message: "{{ trigger.entity_id }} è tornato: soggiorno {{ brightness_soggiorno }}%, camera {{ brightness_camera }}%"

  # ========================================
  # USCITA DA CASA
  # ========================================

  # alias precedente disabilitata: ora lo spegnimento avviene solo dopo 3 minuti di assenza
  # - alias: "Uscita da Casa - Spegni tutte le luci quando entrambi escono"
  #   ...existing code...

  - alias: "Casa Vuota - Spegni Luci dopo 2 minuti"
    mode: single
    description: "Spegni tutte le luci e la TV solo se entrambi sono assenti da almeno 2 minuti"
    trigger:
      - platform: state
        entity_id:
          - device_tracker.moto_g42
          - device_tracker.pixel_9a
        to: "not_home"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: device_tracker.moto_g42
        state: "not_home"
      - condition: state
        entity_id: device_tracker.pixel_9a
        state: "not_home"
    action:
      - service: script.turn_on
        target:
          entity_id: script.scene_casa_all_off
      - service: media_player.turn_off
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
      - service: !secret notify_service
        data:
          title: "🚪 Casa vuota da 2 minuti"
          message: "Luci e TV spente dopo 2 minuti di assenza di tutti."

  # ========================================
  # USCITA SOLO MOTO G42
  # ========================================
  - alias: "Moto G42 Esce - Spegni TV HDMI2 e PC"
    mode: single
    description: "Quando Moto G42 esce da casa, spegni TV se su HDMI2 e spegni PC"
    trigger:
      - platform: state
        entity_id: device_tracker.moto_g42
        from: "home"
        to: "not_home"
    condition:
      # Spegni solo se TV è su HDMI2
      - condition: template
        value_template: >
          {% set src = (state_attr('media_player.lg_webos_tv_oled48c31la', 'source') or '').replace(' ', '').upper() %}
          {{ src == 'HDMI2' }}
    action:
      # Spegni TV
      - service: media_player.turn_off
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
      # Notifica
      - service: !secret notify_service
        data:
          title: "📱 Moto G42 away"
          message: "TV era su HDMI2: spenta"

  # ========================================
  # USCITA SINGOLA - SOLO NOTIFICA
  # ========================================
  - alias: "Uscita Singola - Moto G42 via, Pixel in casa"
    mode: single
    description: "Notifica quando Moto G42 esce ma Pixel 9a è ancora in casa"
    trigger:
      - platform: state
        entity_id: device_tracker.moto_g42
        from: "home"
        to: "not_home"
    condition:
      - condition: state
        entity_id: device_tracker.pixel_9a
        state: "home"
    action:
      - service: !secret notify_service
        data:
          title: "ℹ️ Uscita singola"
          message: "Sei uscito, Pixel 9a è ancora a casa."

  - alias: "Uscita Singola - Pixel via, Moto G42 in casa"
    mode: single
    description: "Notifica quando Pixel 9a esce ma Moto G42 è ancora in casa"
    trigger:
      - platform: state
        entity_id: device_tracker.pixel_9a
        from: "home"
        to: "not_home"
    condition:
      - condition: state
        entity_id: device_tracker.moto_g42
        state: "home"
    action:
      - service: !secret notify_service
        data:
          title: "ℹ️ Uscita singola (Pixel)"
          message: "Pixel 9a è uscito, tu sei in casa."

  # ========================================
  # TV ACCESA CON CASA VUOTA - NOTIFICA
  # ========================================
  - alias: "TV accesa con casa vuota - Notifica"
    mode: single
    description: "Avvisa se la TV resta accesa mentre nessuno è in casa"
    trigger:
      - platform: state
        entity_id: media_player.lg_webos_tv_oled48c31la
        to: "on"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: device_tracker.moto_g42
        state: "not_home"
      - condition: state
        entity_id: device_tracker.pixel_9a
        state: "not_home"
    action:
      - service: !secret notify_service
        data:
          title: "📺 TV accesa a casa vuota"
          message: "La TV è accesa da 2 minuti mentre nessuno è in casa."
