# =========================
# SCRIPT ROBOT
# =========================

# =========================
# AUTOMAZIONI ROBOT
# =========================

automation:
  - id: robot_avvio_casa_vuota
    alias: "Robot - Avvio Pulizia Casa Vuota"
    description: "Avvia la pulizia quando sia {{ !secret mobile_2 }} che {{ !secret mobile_1 }} non sono in casa"
    mode: single
    trigger:
      - platform: state
        entity_id: !secret mobile_2
        to: "not_home"
      - platform: state
        entity_id: !secret mobile_1
        to: "not_home"
    condition:
      - condition: state
        entity_id: !secret mobile_2
        state: "not_home"
      - condition: state
        entity_id: !secret mobile_1
        state: "not_home"
    action:
      - variables:
          segments: [1, 2, 3, 4, 7] # Cameretta, Camera da letto, Corridoio, Soggiorno, Cucina
          random_segments: "{{ segments | shuffle }}"
      - service: dreame_vacuum.vacuum_clean_segment
        data:
          entity_id: vacuum.ufo
          segments: "{{ random_segments }}"
      - service: !secret notify_service
        data:
          title: "Robot"
          message: "Casa vuota - pulizia avviata automaticamente (ordine random e continua)"

  - id: robot_ritorno_base_rientro
    alias: "Robot - Ritorno alla Base al Rientro"
    description: "Riporta il robot alla base quando {{ !secret mobile_2 }} o {{ !secret mobile_1 }} rientrano in casa"
    mode: restart
    trigger:
      - platform: state
        entity_id: !secret mobile_2
        to: "home"
      - platform: state
        entity_id: !secret mobile_1
        to: "home"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.ufo
            state: "docked"
    action:
      - service: vacuum.return_to_base
        target:
          entity_id: vacuum.ufo
      - service: !secret notify_service
        data:
          title: "Robot"
          message: "Qualcuno è rientrato - robot torna alla base"
