# ============================================================
# TV LG WebOS - CONFIGURAZIONE E AUTOMAZIONI
# ============================================================
# Questo file contiene tutta la logica relativa alla TV:
# - Automazioni per l'accensione/spegnimento
# - Sincronizzazione luci TV
# - Controllo WoL
# ============================================================

# ============================================================
# SCRIPT
# ============================================================
script:
  # ========================================
  # HDMI INPUT SELECTION WITH HOME BUTTON
  # ========================================
  select_hdmi_1:
    alias: "Seleziona HDMI 1 (con HOME)"
    sequence:
      # Invia comando HOME
      - service: webostv.button
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          button: HOME
      # Attendi 500ms
      - delay:
          milliseconds: 500
      # Seleziona HDMI 1
      - service: media_player.select_source
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          source: "HDMI 1"
        continue_on_error: true

  select_hdmi_2:
    alias: "Seleziona HDMI 2 (con HOME)"
    sequence:
      # Invia comando HOME
      - service: webostv.button
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          button: HOME
      # Attendi 500ms
      - delay:
          milliseconds: 500
      # Seleziona HDMI 2
      - service: media_player.select_source
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          source: "HDMI 2"
        continue_on_error: true

  select_hdmi_3:
    alias: "Seleziona HDMI 3 (con HOME)"
    sequence:
      # Invia comando HOME
      - service: webostv.button
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          button: HOME
      # Attendi 500ms
      - delay:
          milliseconds: 500
      # Seleziona HDMI 3
      - service: media_player.select_source
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          source: "HDMI 3"
        continue_on_error: true

  select_hdmi_4:
    alias: "Seleziona HDMI 4 (con HOME)"
    sequence:
      # Invia comando HOME
      - service: webostv.button
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          button: HOME
      # Attendi 500ms
      - delay:
          milliseconds: 500
      # Seleziona HDMI 4
      - service: media_player.select_source
        target:
          entity_id: media_player.lg_webos_tv_oled48c31la
        data:
          source: "HDMI 4"
        continue_on_error: true

# ============================================================
# AUTOMATION
# ============================================================
automation:
  - alias: "TV On - Accendi Luci TV a 1%"
    description: "Quando la TV si accende (manualmente), imposta la luce TV a 1%"
    trigger:
      - platform: state
        entity_id: media_player.lg_webos_tv_oled48c31la
        to: "playing"
    condition:
      # Non agire se una scena è in esecuzione (led_bulk_mode attivo)
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
    action:
      - service: script.set_zone_brightness
        data:
          zone_key: "tv"
          brightness: 1
