# ============================================================
# CAMERA DA LETTO - CONTROLLO UNIFICATO LUCI
# ============================================================
# Usa SOLO i due input_number esistenti e fornisce:
# - Una luce virtuale (template) che rappresenta entrambe le luci
# - Automazione di sync tra i due input_number
# - Script hw_* per controllo vocale globale
# ============================================================

# ============================================================
# TEMPLATE LIGHT VIRTUALE - TUTTE LE LUCI CAMERA DA LETTO
# ============================================================
# Sintassi Template Light (HA): state, level, turn_on, turn_off, set_level
# state: on se almeno uno > 0
# level: media 0-100 → 0-255
# set_level: riceve brightness (0-255) e aggiorna entrambi gli input_number
# ============================================================
template:
  - light:
      - name: "hw Tutte Luci Camera da Letto"
        unique_id: light_hw_all_bedroom_lights
        state: >
          {{ (states('input_number.hw_bedroom_sopra_al_letto_level') | int(0) > 0) or
             (states('input_number.hw_bedroom_camera_da_letto_level') | int(0) > 0) }}
        level: >
          {% set avg = (((states('input_number.hw_bedroom_sopra_al_letto_level') | int(0)) + (states('input_number.hw_bedroom_camera_da_letto_level') | int(0))) / 2) | round(0) | int %}
          {{ (avg * 255 / 100) | round(0) | int }}
        turn_on:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.led_bulk_mode
          - service: scene.turn_on
            target:
              entity_id: scene.led_a_u
          - service: script.set_zone_brightness
            data:
              zone_key: "led_sopra_al_letto"
              brightness: 60
          - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
            timeout: "00:00:05"
          - delay: "00:00:00.6"
          - service: scene.turn_on
            target:
              entity_id: scene.led_linea
          - service: script.set_zone_brightness
            data:
              zone_key: "led_camera_da_letto"
              brightness: 60
          - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
            timeout: "00:00:05"
          - delay: "00:00:00.6"
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.led_bulk_mode
        turn_off:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.led_bulk_mode
          - service: script.zone_off
            data:
              zone_key: "led_sopra_al_letto"
          - wait_template: "{{ is_state('script.zone_off','off') }}"
            timeout: "00:00:05"
          - delay: "00:00:00.6"
          - service: script.zone_off
            data:
              zone_key: "led_camera_da_letto"
          - wait_template: "{{ is_state('script.zone_off','off') }}"
            timeout: "00:00:05"
          - delay: "00:00:00.6"
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.led_bulk_mode
        set_level:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.led_bulk_mode
          - variables:
              pct: "{{ (brightness | int(0) * 100 / 255) | round(0) | int }}"
          - service: script.set_zone_brightness
            data:
              zone_key: "led_sopra_al_letto"
              brightness: "{{ pct }}"
          - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
            timeout: "00:00:05"
          - delay: "00:00:00.6"
          - service: script.set_zone_brightness
            data:
              zone_key: "led_camera_da_letto"
              brightness: "{{ pct }}"
          - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
            timeout: "00:00:05"
          - delay: "00:00:00.6"
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.led_bulk_mode

# ============================================================
# AUTOMAZIONI - SINCRONIZZAZIONE INTELLIGENTE
# ============================================================
automation:
  - alias: Luci Bedroom All - Sync Both Zones
    mode: restart
    description: "Quando una zona camera da letto cambia, aggiorna anche l'altra (se non è bulk mode)"
    trigger:
      - platform: state
        entity_id:
          - input_number.hw_bedroom_sopra_al_letto_level
          - input_number.hw_bedroom_camera_da_letto_level
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - variables:
          triggered_value: "{{ states(trigger.entity_id) | int(0) }}"
          other_input: >
            {% if 'sopra_al_letto' in trigger.entity_id %}
              input_number.hw_bedroom_camera_da_letto_level
            {% else %}
              input_number.hw_bedroom_sopra_al_letto_level
            {% endif %}
      - service: input_number.set_value
        target:
          entity_id: "{{ other_input }}"
        data:
          value: "{{ triggered_value }}"
      - delay: "00:00:00.2"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode
# ============================================================
# SCRIPT - COMANDI UNIFICATI PER LA CAMERA DA LETTO
# ============================================================
script:
  hw_bedroom_all_on:
    alias: "Accendi Luci Camera da Letto"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.set_zone_preset
        data:
          zone_key: "led_sopra_al_letto"
          preset_level: "default"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: script.set_zone_preset
        data:
          zone_key: "led_camera_da_letto"
          preset_level: "default"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  hw_bedroom_all_lights_off:
    alias: "Spegni Luci Camera da Letto"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.zone_off
        data:
          zone_key: "led_sopra_al_letto"
      - delay: "00:00:00.6"
      - service: script.zone_off
        data:
          zone_key: "led_camera_da_letto"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  hw_bedroom_all_lights_low:
    alias: "Camera da Letto Bassa"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.set_zone_preset
        data:
          zone_key: "led_sopra_al_letto"
          preset_level: "low"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: script.set_zone_preset
        data:
          zone_key: "led_camera_da_letto"
          preset_level: "low"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  hw_bedroom_all_lights_medium:
    alias: "Camera da Letto Media"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.set_zone_preset
        data:
          zone_key: "led_sopra_al_letto"
          preset_level: "medium"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: script.set_zone_preset
        data:
          zone_key: "led_camera_da_letto"
          preset_level: "medium"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  hw_bedroom_all_lights_high:
    alias: "Camera da Letto Alta"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.set_zone_preset
        data:
          zone_key: "led_sopra_al_letto"
          preset_level: "high"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: script.set_zone_preset
        data:
          zone_key: "led_camera_da_letto"
          preset_level: "high"
      - wait_template: "{{ is_state('script.set_zone_preset','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  hw_bedroom_all_lights_up:
    alias: "Aumenta Luci Camera da Letto"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.set_zone_brightness
        data:
          zone_key: "led_sopra_al_letto"
          brightness: >
            {% set current = states('input_number.hw_bedroom_sopra_al_letto_level') | int(0) %}
            {% set new_val = current + 10 %}
            {% if new_val > 100 %}100{% elif new_val < 0 %}0{% else %}{{ new_val }}{% endif %}
      - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: script.set_zone_brightness
        data:
          zone_key: "led_camera_da_letto"
          brightness: >
            {% set current = states('input_number.hw_bedroom_camera_da_letto_level') | int(0) %}
            {% set new_val = current + 10 %}
            {% if new_val > 100 %}100{% elif new_val < 0 %}0{% else %}{{ new_val }}{% endif %}
      - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  hw_bedroom_all_lights_down:
    alias: "Diminuisci Luci Camera da Letto"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - service: script.set_zone_brightness
        data:
          zone_key: "led_sopra_al_letto"
          brightness: >
            {% set current = states('input_number.hw_bedroom_sopra_al_letto_level') | int(0) %}
            {% set new_val = current - 10 %}
            {% if new_val > 100 %}100{% elif new_val < 0 %}0{% else %}{{ new_val }}{% endif %}
      - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: script.set_zone_brightness
        data:
          zone_key: "led_camera_da_letto"
          brightness: >
            {% set current = states('input_number.hw_bedroom_camera_da_letto_level') | int(0) %}
            {% set new_val = current - 10 %}
            {% if new_val > 100 %}100{% elif new_val < 0 %}0{% else %}{{ new_val }}{% endif %}
      - wait_template: "{{ is_state('script.set_zone_brightness','off') }}"
        timeout: "00:00:05"
      - delay: "00:00:00.6"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode
