# ============================================================
# AUTOMATION STANZA-SPECIFICA (CUCINA)
# ============================================================
automation:
  - alias: Luci Zone Brightness - Cucina
    mode: restart
    description: "Monitora cambiamenti input_number zone cucina"
    trigger:
      - platform: state
        entity_id:
          - input_number.cucina_led_level
          - input_number.cucina_gregg_level
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
      # Ignora trigger a brightness 0 dallo slider (usa pulsante off per spegnere)
      - condition: template
        value_template: "{{ states(trigger.entity_id) | int(0) > 0 }}"
    action:
      - variables:
          zone_key: >-
            {% set raw = trigger.entity_id.split('cucina_')[-1].split('_level')[0] %}
            {% set map = {'led': 'led_cucina', 'gregg': 'gregg_cucina'} %}
            {{ map.get(raw, raw) }}
      - service: script.set_zone_brightness
        data:
          zone_key: "{{ zone_key }}"
          brightness: "{{ states(trigger.entity_id) | int }}"

  - alias: Luci Device Brightness Sync - Cucina
    description: "Sincronizza gli input_number quando si modifica la luminosità della luce fisica (UI/telecomando) sulla zona selezionata"
    trigger:
      - platform: state
        entity_id: light.luci
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
      - condition: template
        value_template: "{{ states('input_text.ultima_zona_led') in ['Luce Cucina','Gregg Cucina'] }}"
    action:
      - delay: "00:00:00.3"
      - variables:
          # Se luce è off, brightness_pct = 0, altrimenti calcola da attributo
          brightness_pct: >-
            {% if is_state('light.luci', 'off') or state_attr('light.luci', 'brightness') in [None, ''] %}
              0
            {% else %}
              {{ ((state_attr('light.luci','brightness') | int(0)) * 100 / 255) | round(0) }}
            {% endif %}
          zona: "{{ states('input_text.ultima_zona_led') }}"
          input_map:
            {
              "Luce Cucina": "input_number.cucina_led_level",
              "Gregg Cucina": "input_number.cucina_gregg_level",
            }
          target_input: "{{ input_map[zona] }}"
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - delay: "00:00:00.1"
      - service: input_number.set_value
        target:
          entity_id: "{{ target_input }}"
        data:
          value: "{{ brightness_pct | int }}"
      - delay: "00:00:00.2"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

# ============================================================
# BINARY SENSORS - UI HELPERS (CUCINA)
# ============================================================
template:
  - binary_sensor:
      - name: "zona_led_cucina_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Luce Cucina'
             and states('light.luci') == 'on' }}

      - name: "zona_gregg_cucina_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Gregg Cucina'
             and states('light.luci') == 'on' }}

      - name: "zona_cucina_slider_visibile"
        state: >
          {% set ultima = states('input_text.ultima_zona_led') %}
          {{ ultima != '' and ultima in ['Luce Cucina','Gregg Cucina'] }}

# ============================================================
# INPUT_NUMBER - ZONE BRIGHTNESS SLIDERS
# ============================================================
input_number:
  cucina_led_level:
    name: "Livello Luce Cucina"
    min: 0
    max: 100
    step: 1

  cucina_gregg_level:
    name: "Livello Gregg Cucina"
    min: 0
    max: 100
    step: 1

script:
  # ========================================
  # HELPER SCRIPT - CAMBIO ZONA CON BULK MODE
  # ========================================
  select_zone_cucina:
    alias: "Seleziona Zona Cucina (con protezione bulk)"
    mode: restart
    fields:
      zone_name:
        description: "Nome della zona da selezionare"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - delay: "00:00:00.1"
      - service: input_text.set_value
        target:
          entity_id: input_text.ultima_zona_led
        data:
          value: "{{ zone_name }}"
      - delay: "00:00:00.3"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  # ========================================
  # WRAPPER SCRIPTS - LUCE CUCINA
  # ========================================
  cucina_led_accesa:
    alias: "Accendi Luce Cucina"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "led_cucina"

  cucina_led_bassa:
    alias: "Luce Cucina Bassa"
    mode: queued
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_cucina"
          preset_level: "low"

  cucina_led_media:
    alias: "Luce Cucina Media"
    mode: queued
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_cucina"
          preset_level: "medium"

  cucina_led_alta:
    alias: "Luce Cucina Alta"
    mode: queued
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_cucina"
          preset_level: "high"

  cucina_led_spenta:
    alias: "Spegni Luce Cucina"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "led_cucina"

  cucina_led_alza:
    alias: "Aumenta Luce Cucina"
    mode: queued
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "led_cucina"
          delta: 10

  cucina_led_abbassa:
    alias: "Diminuisci Luce Cucina"
    mode: queued
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "led_cucina"
          delta: -10

  # ========================================
  # WRAPPER SCRIPTS - GREGG CUCINA
  # ========================================
  cucina_gregg_accesa:
    alias: "Accendi Gregg Cucina"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "gregg_cucina"

  cucina_gregg_bassa:
    alias: "Gregg Cucina Bassa"
    mode: queued
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "gregg_cucina"
          preset_level: "low"

  cucina_gregg_media:
    alias: "Gregg Cucina Media"
    mode: queued
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "gregg_cucina"
          preset_level: "medium"

  cucina_gregg_alta:
    alias: "Gregg Cucina Alta"
    mode: queued
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "gregg_cucina"
          preset_level: "high"

  cucina_gregg_spenta:
    alias: "Spegni Gregg Cucina"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "gregg_cucina"

  cucina_gregg_alza:
    alias: "Aumenta Gregg Cucina"
    mode: queued
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "gregg_cucina"
          delta: 10

  cucina_gregg_abbassa:
    alias: "Diminuisci Gregg Cucina"
    mode: queued
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "gregg_cucina"
          delta: -10
