# ============================================================
# AUTOMATION STANZA-SPECIFICA (SOGGIORNO LUCI)
# ============================================================
automation:
  - alias: Luci Zone Brightness - Soggiorno
    mode: restart
    description: "Monitora cambiamenti input_number zone led_soggiorno"
    trigger:
      - platform: state
        entity_id:
          - input_number.soggiorno_led_level
          - input_number.soggiorno_tv_level
          - input_number.soggiorno_museo_level
          - input_number.soggiorno_libreria_level
          - input_number.soggiorno_gregg_level
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
      # Ignora trigger a brightness 0 dallo slider (usa pulsante off per spegnere)
      - condition: template
        value_template: "{{ states(trigger.entity_id) | int(0) > 0 }}"
    action:
      - variables:
          zone_key: >-
            {% set raw = trigger.entity_id.split('soggiorno_')[-1].split('_level')[0] %}
            {% set map = {'led': 'led_soggiorno', 'tv': 'tv', 'museo': 'museo', 'libreria': 'libreria', 'gregg': 'gregg_soggiorno'} %}
            {{ map.get(raw, raw) }}
      - service: script.set_zone_brightness
        data:
          zone_key: "{{ zone_key }}"
          brightness: "{{ states(trigger.entity_id) | int }}"

  - alias: Luci Device Brightness Sync - Soggiorno
    description: "Sincronizza gli input_number quando si modifica la luminosità della luce fisica (UI/telecomando) sulla zona selezionata"
    trigger:
      - platform: state
        entity_id: light.luci
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
      - condition: template
        value_template: "{{ states('input_text.ultima_zona_led') in ['Soggiorno','TV','Museo','Libreria','Gregg Soggiorno'] }}"
    action:
      - delay: "00:00:00.3"
      - variables:
          # Se luce è off, brightness_pct = 0, altrimenti calcola da attributo
          brightness_pct: >-
            {% if is_state('light.luci', 'off') or state_attr('light.luci', 'brightness') in [None, ''] %}
              0
            {% else %}
              {{ ((state_attr('light.luci','brightness') | int(0)) * 100 / 255) | round(0) }}
            {% endif %}
          zona: "{{ states('input_text.ultima_zona_led') }}"
          input_map:
            {
              "Soggiorno": "input_number.soggiorno_led_level",
              "TV": "input_number.soggiorno_tv_level",
              "Museo": "input_number.soggiorno_museo_level",
              "Libreria": "input_number.soggiorno_libreria_level",
              "Gregg Soggiorno": "input_number.soggiorno_gregg_level",
            }
          target_input: "{{ input_map[zona] }}"
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - delay: "00:00:00.1"
      - service: input_number.set_value
        target:
          entity_id: "{{ target_input }}"
        data:
          value: "{{ brightness_pct | int }}"
      - delay: "00:00:00.2"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

# ============================================================
# BINARY SENSORS - UI HELPERS (SOGGIORNO)
# ============================================================
template:
  - binary_sensor:
      - name: "zona_in_alto_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Soggiorno'
             and states('light.luci') == 'on' }}

      - name: "zona_tv_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'TV'
             and states('light.luci') == 'on' }}

      - name: "zona_museo_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Museo'
             and states('light.luci') == 'on' }}

      - name: "zona_libreria_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Libreria'
             and states('light.luci') == 'on' }}

      - name: "zona_gregg_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Gregg Soggiorno'
             and states('light.luci') == 'on' }}

      - name: "zona_soggiorno_slider_visibile"
        state: >
          {% set ultima = states('input_text.ultima_zona_led') %}
          {{ ultima != '' and ultima in ['Soggiorno','TV','Museo','Libreria','Gregg Soggiorno'] }}

# ============================================================
# INPUT_NUMBER - ZONE BRIGHTNESS SLIDERS
# ============================================================
input_number:
  soggiorno_led_level:
    name: "Livello Luce Soggiorno"
    min: 0
    max: 100
    step: 1

  soggiorno_tv_level:
    name: "Livello TV"
    min: 0
    max: 100
    step: 1

  soggiorno_museo_level:
    name: "Livello Museo"
    min: 0
    max: 100
    step: 1

  soggiorno_libreria_level:
    name: "Livello Libreria"
    min: 0
    max: 100
    step: 1

  soggiorno_gregg_level:
    name: "Livello Gregg Soggiorno"
    min: 0
    max: 100
    step: 1

script:
  # ========================================
  # HELPER SCRIPT - CAMBIO ZONA CON BULK MODE
  # ========================================
  select_zone_soggiorno:
    alias: "Seleziona Zona Soggiorno (con protezione bulk)"
    mode: restart
    fields:
      zone_name:
        description: "Nome della zona da selezionare"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - delay: "00:00:00.1"
      - service: input_text.set_value
        target:
          entity_id: input_text.ultima_zona_led
        data:
          value: "{{ zone_name }}"
      - delay: "00:00:00.3"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

  # ========================================
  # WRAPPER SCRIPTS - LUCE SOGGIORNO
  # ========================================
  soggiorno_led_accesa:
    alias: "Accendi Luce Soggiorno"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "led_soggiorno"

  soggiorno_led_bassa:
    alias: "Luce Soggiorno Bassa"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_soggiorno"
          preset_level: "low"

  soggiorno_led_media:
    alias: "Luce Soggiorno Media"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_soggiorno"
          preset_level: "medium"

  soggiorno_led_alta:
    alias: "Luce Soggiorno Alta"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_soggiorno"
          preset_level: "high"

  soggiorno_led_spenta:
    alias: "Spegni Luce Soggiorno"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "led_soggiorno"

  soggiorno_led_alza:
    alias: "Aumenta Luce Soggiorno"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "led_soggiorno"
          delta: 10

  soggiorno_led_abbassa:
    alias: "Diminuisci Luce Soggiorno"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "led_soggiorno"
          delta: -10

  # ========================================
  # WRAPPER SCRIPTS - TV
  # ========================================
  soggiorno_tv_accesa:
    alias: "Accendi Luce TV"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "tv"

  soggiorno_tv_bassa:
    alias: "Luce TV Bassa"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "tv"
          preset_level: "low"

  soggiorno_tv_media:
    alias: "Luce TV Media"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "tv"
          preset_level: "medium"

  soggiorno_tv_alta:
    alias: "Luce TV Alta"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "tv"
          preset_level: "high"

  soggiorno_tv_spenta:
    alias: "Spegni TV"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "tv"

  soggiorno_tv_alza:
    alias: "Aumenta TV"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "tv"
          delta: 10

  soggiorno_tv_abbassa:
    alias: "Diminuisci TV"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "tv"
          delta: -10

  # ========================================
  # WRAPPER SCRIPTS - MUSEO
  # ========================================
  soggiorno_museo_accesa:
    alias: "Accendi Luce Museo"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "museo"

  soggiorno_museo_bassa:
    alias: "Luce Museo Bassa"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "museo"
          preset_level: "low"

  soggiorno_museo_media:
    alias: "Luce Museo Media"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "museo"
          preset_level: "medium"

  soggiorno_museo_alta:
    alias: "Luce Museo Alta"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "museo"
          preset_level: "high"

  soggiorno_museo_spenta:
    alias: "Spegni Museo"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "museo"

  soggiorno_museo_alza:
    alias: "Aumenta Museo"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "museo"
          delta: 10

  soggiorno_museo_abbassa:
    alias: "Diminuisci Museo"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "museo"
          delta: -10

  # ========================================
  # WRAPPER SCRIPTS - LIBRERIA
  # ========================================
  soggiorno_libreria_accesa:
    alias: "Accendi Luce Libreria"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "libreria"

  soggiorno_libreria_bassa:
    alias: "Luce Libreria Bassa"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "libreria"
          preset_level: "low"

  soggiorno_libreria_media:
    alias: "Luce Libreria Media"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "libreria"
          preset_level: "medium"

  soggiorno_libreria_alta:
    alias: "Luce Libreria Alta"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "libreria"
          preset_level: "high"

  soggiorno_libreria_spenta:
    alias: "Spegni Libreria"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "libreria"

  soggiorno_libreria_alza:
    alias: "Aumenta Libreria"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "libreria"
          delta: 10

  soggiorno_libreria_abbassa:
    alias: "Diminuisci Libreria"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "libreria"
          delta: -10

  # ========================================
  # WRAPPER SCRIPTS - GREGG SOGGIORNO
  # ========================================
  soggiorno_gregg_accesa:
    alias: "Accendi Gregg Soggiorno"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "gregg_soggiorno"

  soggiorno_gregg_bassa:
    alias: "Gregg Soggiorno Bassa"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "gregg_soggiorno"
          preset_level: "low"

  soggiorno_gregg_media:
    alias: "Gregg Soggiorno Media"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "gregg_soggiorno"
          preset_level: "medium"

  soggiorno_gregg_alta:
    alias: "Gregg Soggiorno Alta"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "gregg_soggiorno"
          preset_level: "high"

  soggiorno_gregg_spenta:
    alias: "Spegni Gregg Soggiorno"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "gregg_soggiorno"

  soggiorno_gregg_alza:
    alias: "Aumenta Gregg Soggiorno"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "gregg_soggiorno"
          delta: 10

  soggiorno_gregg_abbassa:
    alias: "Diminuisci Gregg Soggiorno"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "gregg_soggiorno"
          delta: -10
