# ============================================================
# AUTOMATION STANZA-SPECIFICA (CAMERETTA)
# ============================================================
automation:
  - alias: Luci Zone Brightness - Cameretta
    mode: restart
    description: "Monitora cambiamenti input_number zone cameretta"
    trigger:
      - platform: state
        entity_id:
          - input_number.cameretta_led_level
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
      # Ignora trigger a brightness 0 dallo slider (usa pulsante off per spegnere)
      - condition: template
        value_template: "{{ states(trigger.entity_id) | int(0) > 0 }}"
    action:
      - service: script.set_zone_brightness
        data:
          zone_key: "led_cameretta"
          brightness: "{{ states(trigger.entity_id) | int }}"

  - alias: Luci Device Brightness Sync - Cameretta
    description: "Sincronizza gli input_number quando si modifica la luminosità della luce fisica (UI/telecomando) sulla zona selezionata"
    trigger:
      - platform: state
        entity_id: light.luci
    condition:
      - condition: state
        entity_id: input_boolean.led_bulk_mode
        state: "off"
      - condition: template
        value_template: "{{ states('input_text.ultima_zona_led') == 'Luce Cameretta' }}"
    action:
      - variables:
          # Se luce è off, brightness_pct = 0, altrimenti calcola da attributo
          brightness_pct: >-
            {% if is_state('light.luci', 'off') or state_attr('light.luci', 'brightness') in [None, ''] %}
              0
            {% else %}
              {{ ((state_attr('light.luci','brightness') | int(0)) * 100 / 255) | round(0) }}
            {% endif %}
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.led_bulk_mode
      - delay: "00:00:00.1"
      - service: input_number.set_value
        target:
          entity_id: input_number.cameretta_led_level
        data:
          value: "{{ brightness_pct | int }}"
      - delay: "00:00:00.2"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.led_bulk_mode

# ============================================================
# BINARY SENSORS - UI HELPERS (CAMERETTA)
# ============================================================
template:
  - binary_sensor:
      - name: "zona_led_cameretta_accesa"
        state: >
          {{ states('input_text.ultima_zona_led') == 'Luce Cameretta'
             and states('light.luci') == 'on' }}

      - name: "zona_cameretta_slider_visibile"
        state: >
          {% set ultima = states('input_text.ultima_zona_led') %}
          {{ ultima != '' and ultima == 'Luce Cameretta' }}

# ============================================================
# INPUT_NUMBER - ZONE BRIGHTNESS SLIDERS
# ============================================================
input_number:
  cameretta_led_level:
    name: "Livello Luce Cameretta"
    min: 0
    max: 100
    step: 1

script:
  # ========================================
  # WRAPPER SCRIPTS - LUCE CAMERETTA
  # ========================================
  cameretta_led_accesa:
    alias: "Accendi Luce Cameretta"
    sequence:
      - service: script.zone_on
        data:
          zone_key: "led_cameretta"

  cameretta_led_basse:
    alias: "Luce Cameretta Bassa"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_cameretta"
          preset_level: "low"

  cameretta_led_medie:
    alias: "Luce Cameretta Media"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_cameretta"
          preset_level: "medium"

  cameretta_led_alte:
    alias: "Luce Cameretta Alta"
    sequence:
      - service: script.set_zone_preset
        data:
          zone_key: "led_cameretta"
          preset_level: "high"

  cameretta_led_spenta:
    alias: "Spegni Luce Cameretta"
    sequence:
      - service: script.zone_off
        data:
          zone_key: "led_cameretta"

  cameretta_led_alza:
    alias: "Aumenta Luce Cameretta"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "led_cameretta"
          delta: 10

  cameretta_led_abbassa:
    alias: "Diminuisci Luce Cameretta"
    sequence:
      - service: script.adjust_zone_level
        data:
          zone_key: "led_cameretta"
          delta: -10
